apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: Prometheus
    url: http://host.docker.internal:9090
    isDefault: true
    jsonData:
      httpMethod: POST
    editable: true

