security:
  enable_auth: false

database:
  file:
    folder: /perses
    extension: yaml

provisioning:
  folders:
  - /provisioning

schemas:
  panels_path: "/etc/perses/cue/schemas/panels"
  queries_path: "/etc/perses/cue/schemas/queries"
  datasources_path: "/etc/perses/cue/schemas/datasources"
  variables_path: "/etc/perses/cue/schemas/variables"
  interval: "5m"

important_dashboards:
  - project: "Demo"
    dashboard: "Demo"

information: |-
  # Hello World
